---
- hosts: localhost
  connection: local
  roles:
      - role: generate_keys
  tags:
      - local

- hosts: ossec_server
  become: yes
  become_method: sudo
  roles:
      - role: ansible-role-java
        when: "ansible_os_family == 'RedHat'"
        java_packages:
          - java-1.8.0-openjdk
      - role: ossec-server
  tags:
      - server

- hosts: ossec_linux_agents
  become: yes
  become_method: sudo
  roles:
      - role: ossec-linux-agent
  tags:
      - linux_agent

- hosts: ossec_windows_agents
  roles:
      - role: ossec-windows-agent
  tags:
      - windows_agent
