# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # VM  OSSSEC SERVER
    config.vm.define "ossecserver" do |ossecserver|
        ossecserver.vm.box = "nrel/CentOS-6.5-x86_64"
        ossecserver.vm.network "private_network", ip: "10.10.1.10"
        ossecserver.vm.provision "shell", inline: <<-SHELL
            #sudo iptables --flush
            #sudo chkconfig iptables off
            sudo service iptables save
            sudo service iptables stop
            sudo chkconfig iptables off
        SHELL

        # VirtualBox.
        ossecserver.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
            virtualbox.customize ["modifyvm", :id, "--name", "ossecserver"]
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end

    # VM  agent linux CentOS
    config.vm.define "agent1" do |agent1|
        agent1.vm.box = "nrel/CentOS-6.5-x86_64"
        agent1.vm.network "private_network", ip: "10.10.1.101"
        agent1.vm.provision "shell", inline: <<-SHELL
            #sudo iptables --flush
            #sudo chkconfig iptables off
            sudo service iptables save
            sudo service iptables stop
            sudo chkconfig iptables off
        SHELL


        # VirtualBox.
        agent1.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
            virtualbox.customize ["modifyvm", :id, "--name", "agent1"]
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end

    # VM pour agent linux Ubuntu
    config.vm.define "agent2" do |agent2|
        agent2.vm.box = "hashicorp/precise64"
        agent2.vm.network "private_network", ip: "10.10.1.102"
        agent2.vm.provision "shell", inline: <<-SHELL
            sudo apt-get -y install apache2
        SHELL

        # VirtualBox.
        agent2.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
            virtualbox.customize ["modifyvm", :id, "--name", "agent2"]
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end

    # VM pour agent Windows
    config.vm.define "agent3" do |agent3|
        agent3.vm.box = "williamtsoi/windows_10"
        agent3.vm.network "private_network", ip: "10.10.1.103"

        # VirtualBox.
        agent3.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
            virtualbox.customize ["modifyvm", :id, "--name", "agent3"]
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end

	config.vm.define "provisioner" do |provisioner|
        provisioner.vm.box = "hashicorp/precise64"
        provisioner.vm.network "private_network", ip: "10.10.1.9"
        provisioner.vm.provision "file", source: "../../ossec-elk-ansible-vagrant/", destination: "~/ossec-ansible"
        provisioner.vm.provision "shell", inline: <<-SHELL
        	sudo apt-get update && sudo apt-get upgrade
        	sudo apt-get -y install git python-pip sshpass
        	sudo pip install xmltodict pywinrm markupsafe ansible
        	cd ossec-ansible/provisioning && ansible-playbook -i hosts_vagrant playbook_vagrant.yml
        SHELL

        # VirtualBox.
        provisioner.vm.provider :virtualbox do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #    virtualbox.customize ["modifyvm", :id, "--memory", 1024]
            virtualbox.customize ["modifyvm", :id, "--name", "provisioner"]
            virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end
end
